# Generated by Django 6.1.1 on 2026-09-05 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('domain', models.CharField(blank=True, max_length=100)),
                ('stage', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_type', models.CharField(blank=True, max_length=100)),
                ('features', models.TextField(blank=True)),
                ('target_users', models.CharField(blank=True, max_length=255)),
                ('expected_users', models.CharField(blank=True, max_length=100)),
                ('tech_preferences', models.TextField(blank=True)),
                ('infrastructure_requirements', models.TextField(blank=True)),
                ('security_requirements', models.TextField(blank=True)),
                ('scalability_requirements', models.TextField(blank=True)),
                ('additional_requirements', models.TextField(blank=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requirement', to='projects.project')),
            ],
        ),
    ]
