# Generated by Django 6.1.1 on 2026-09-05 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchitectureReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('technology_stack', models.JSONField(blank=True, null=True)),
                ('database_design', models.JSONField(blank=True, null=True)),
                ('api_architecture', models.JSONField(blank=True, null=True)),
                ('cloud_architecture', models.JSONField(blank=True, null=True)),
                ('security_checklist', models.JSONField(blank=True, null=True)),
                ('scalability_strategy', models.JSONField(blank=True, null=True)),
                ('diagram_data', models.TextField(blank=True, null=True)),
                ('architecture_score', models.IntegerField(blank=True, null=True)),
                ('strengths', models.JSONField(blank=True, null=True)),
                ('risks', models.JSONField(blank=True, null=True)),
                ('improvements', models.JSONField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='architecture_reports', to='projects.project')),
            ],
        ),
    ]
